[package]
name = "se_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
crossbeam-channel = "0.5.6"